// Centralized icon imports. Add new icons here to keep tree-shaking efficient.
export {
  Search as SearchIcon,
  NotificationsOutline as BellIcon,
  PersonCircleOutline as UserIcon,
  SunnyOutline as SunIcon,
  MoonOutline as MoonIcon,
  DesktopOutline as AutoIcon,
  MenuOutline as MenuIcon,
  ChatbubblesOutline as ChatIcon,
  LibraryOutline as KnowledgeIcon,
  TicketOutline as TicketIcon,
  AddOutline as AddIcon,
  EllipsisHorizontal as MoreIcon,
  CopyOutline as CopyIcon,
  RefreshOutline as RefreshIcon,
  ThumbsUpOutline as ThumbsUpIcon,
  ThumbsDownOutline as ThumbsDownIcon,
  ArrowDownOutline as ArrowDownIcon,
  SendOutline as SendIcon,
  StopCircleOutline as StopIcon,
  BulbOutline as BulbIcon,
  ConstructOutline as ToolIcon,
  CheckmarkCircleOutline as CheckIcon,
  AlertCircleOutline as AlertIcon,
} from '@vicons/ionicons5';
